### ISSUE TITLE
Panic error decoding ENR from Gnosis Network

### ISSUE THREAD

**Issue by cortze** [migalabs/armiarma#43]
## Decription
The Gnosis Crawler we are running for the dashboard crashed for a panic error while decoding an ENR
go_version = `go1.17.2 linux/amd64`
crawler version/commit =  `origin/feature/filecoin-network-support` -> `0b2a29d1a5d9a283bc9d5174183f037bb1cbd11a`

## Error Log
```
panic: invalid node: missing 'enr:' prefix for base64-encoded record

goroutine 126 [running]:
github.com/ethereum/go-ethereum/p2p/enode.MustParse({0x0, 0x27})
        /home/crawler/go/pkg/mod/github.com/ethereum/go-ethereum@v1.10.8/p2p/enode/node.go:58 +0x7a
github.com/migalabs/armiarma/src/peering.(*PruningStrategy).peerstoreIteratorRoutine(0xc001b90000)
        /home/crawler/armiarma/src/peering/pruning_strategy.go:170 +0xb97
created by github.com/migalabs/armiarma/src/peering.(*PruningStrategy).Run
        /home/crawler/armiarma/src/peering/pruning_strategy.go:108 +0x5f
```
## Solution
Avoid raising a Panic error when ENR are not parseable -> remove the ENR or even the peer instead

**Comment by cortze** [comment]
closing this, as it is solved in #52
